### ISSUE TITLE
UnboundLocalError: local variable 'adv_class' referenced before assignment

### ISSUE THREAD

**Issue by muzihuole** [fsept11/FoolHD#3]
Hello, when I run `sh run.sh`, there is an error as follow:
```
==================Creating adversarial example=================
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 77, in main
    train_gae_untargeted(gae_model, adv_model, dataset, gae_optimizer, opt.start, opt.end, **params)
  File "/user-data/FoolHD/code/utils/nn_gae_untargeted.py", line 185, in train_gae
    return adv_class
UnboundLocalError: local variable 'adv_class' referenced before assignment
```
Hope to get your reply. Thank you.

**Comment by fsepteixeira** [comment]
Hi!

It seems that in your test the dataloader didn't contain any samples. Because of it, it did not go inside the loop where adv_class variable is initialized. 
You can solve the error simply by removing the return statement (it's really not doing anything there actually), but there is probably something else going on with you dataloader.

**Comment by muzihuole** [comment]
Thanks for your reply. 
I found the reason of this error is that I did not modify the location of the data set. I'm very sorry for my low-level mistakes. After I set the correct data set location, the code can run successfully.
I will close this issue. Thank you.
